import Head from "next/head";
import Banner from "../components/Banner";
import TabsGroup from "../components/TabsGroup";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home({ categoryList, articleList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bloggie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Banner />
      <TabsGroup categoryList={categoryList} articleList={articleList} />
    </div>
  );
}

export const getStaticProps = async (ctx) => {
  const cat = await axios.get(`${process.env.BASE_URL}/api/categories`);
  const articles = await axios.get(`${process.env.BASE_URL}/api/articles`);

  return {
    props: {
      categoryList: cat.data,
      articleList: articles.data,
    },
    revalidate: 10,
  };
};
